default_dependencies: false
targets:
  ubuntu-24.04:
    dependencies:
      - libpq5
      - libxml2
      - libxslt1.1
  ubuntu-22.04:
    dependencies:
      - libpq5
      - libxml2
      - libxslt1.1
  ubuntu-20.04:
    dependencies:
      - libpq5
      - libxml2
      - libxslt1.1
  debian-11:
    dependencies:
      - libpq5
      - libxml2
      - libxslt1.1
  debian-12:
    dependencies:
      - libpq5
      - libxml2
      - libxslt1.1
